#
# https://www.home-assistant.io/docs/automation/
#
# This include is for the automations editor/UI
automation: !include ../automations.yaml
automation split: !include_dir_merge_list ../automations/list