#
# https://hacf.fr/installation-influxdb-home-assistant/
# https://github.com/hassio-addons/addon-influxdb
# https://github.com/hassio-addons/addon-grafana
# https://www.home-assistant.io/integrations/influxdb/
#
influxdb:

  # This is the Hass.io add-on slug, allowing a direct connection to the addon.
  host: a0d7b954-influxdb
  port: 8086
  
  # Le nom de la base de données dans laquelle stocker tous les métriques.
  database: homeassistantDB

  # Informations d'identification.
  username: !secret influxdb_user
  password: !secret influxdb_password

  # Nombre maximum d'essai en cas d'échec.
  max_retries: 3

  # The list of attribute names which should be reported as tags
  # and not fields to InfluxDB.
  # I've added `device_class` tag.
  # tags_attributes:
  #   - device_class

  default_measurement: state

  # Je préfère spécifier une "whitelist" où je défini seulement les entités que
  # je veux historiser pour garder la base de données la plus légère et propre
  # que possible.
  include: ## Seules les entités listées seront sauvegardées
    entities: !include_dir_merge_list ../influxdb
