#
# https://www.home-assistant.io/components/http/
#
http:
  # Enables additional IP filtering.
  # ip_ban_enabled: true

  # Number of failed login attempts from a single IP after which it will
  # be automatically banned.
  # login_attempts_threshold: 4