#
# Intégrations de tous les dashboards
#
# https://www.home-assistant.io/lovelace/
# https://www.home-assistant.io/lovelace/dashboards-and-views
#
lovelace:
  # Il s'agit du mode de stockage par défaut.
  mode: yaml

  # Inclusion des ressources externes
  # Ajouter uniquement lorsque le mode est défini à yaml
  # Sinon gérer les ressources dans le panneau de configuration Lovelace.
  resources:
    - url: /hacsfiles/lovelace-meteofrance-weather-card/meteofrance-weather-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/custom-sidebar/custom-sidebar.js
      type: module
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module

  # Tableaux de bord Lovelace supplémentaires basés sur YAML
  dashboards: !include ../lovelace/dashboards.yaml
