#
# https://www.home-assistant.io/integrations/plant
#
plant:
  fragaria_ananassa:
    sensors:
      moisture: sensor.xiaomi_miflora_moisture
      temperature: sensor.xiaomi_miflora_temperature
      conductivity: sensor.xiaomi_miflora_soil_conductivity
      brightness: sensor.xiaomi_miflora_illuminance