#
# Script de notification sur A8 (Sylvain)
#
notify_sm_a530f_sg:
  description: 'Envoi une notification'
  fields:
    title:
      description: 'Le titre de la notification'
      example: 'L''état a changé'
    message:
      description: 'Le contenu du message'
      example: 'La lampe est allumée !'
  sequence:
    - service: notify.mobile_app_sm_a530f_sg
      data:
        title: "{{ title }}"
        message: "{{ message }}"
