- mode: single
  alias: "Gestion lumière Cassie : Allume les LED par le bouton IKEA"
  description: 'Allume les LED par le bouton IKEA'
  trigger:
  - platform: device
    domain: mqtt
    device_id: 798eac867a40d6db1382190943d28fbb
    type: click
    subtype: 'on'
    discovery_id: 0xb4e3f9fffe890508 click_on
  condition: []
  action:
  - type: turn_on
    device_id: 9b5fbbc64c27d898d1a4351672a50d7e
    entity_id: light.wled
    domain: light
- mode: single
  alias: "Gestion lumière Cassie : Eteint les LED par le bouton IKEA"
  description: 'Eteint les LED par le bouton IKEA'
  trigger:
  - platform: device
    domain: mqtt
    device_id: 798eac867a40d6db1382190943d28fbb
    type: click
    subtype: 'off'
    discovery_id: 0xb4e3f9fffe890508 click_off
  condition: []
  action:
  - type: turn_off
    device_id: 9b5fbbc64c27d898d1a4351672a50d7e
    entity_id: light.wled
    domain: light