# These are the infrastructure entities that I want
# to store into InfluxDB.
#
# I like to specify (whitelist) each entity to store,
# since that keeps my InfluxDB clean and small.
#
- sensor.aqara_1_humidity