homeassistant:
  name: Maison
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_time_zone
  external_url: !secret homeassistant_url_externe
  internal_url:  !secret homeassistant_url_interne

  packages: !include_dir_named integrations

# logger:
#   default: warning
#   logs:
#     homeassistant.components.webhook: debug

#mqtt: 
#  broker: core-mosquitto 
#  discovery: true

# group: !include groups.yaml
# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml
