
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: warning
  logs:
    homeassistant.components.webhook: debug

#: 
#  broker: core-mosquitto 
#  discovery: true

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html