homeassistant:
  name: Maison
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_time_zone
  # external_url: !secret homeassistant_url_externe
  internal_url:  !secret homeassistant_url_interne

  packages: !include_dir_named integrations

frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js

input_boolean: !include_dir_merge_named entities/inputs/boolean/
input_number: !include_dir_merge_named entities/inputs/number/