#
# Définition de la vue avec les accès autorisés
#
path: batteries
icon: 'mdi:battery'
visible: !include_dir_list ../visibility
badges: []
cards:
  # - !include ../cards/aqara_temp_sdb_battery.yaml
  # - !include ../cards/controlCenter_battery.yaml
  # - !include ../cards/sm_a530f_sg_battery.yaml
  - !include ../cards/batteries-state.yaml