#
# Définition de la vue avec les accès autorisés
#
path: freebox_bt
icon: 'mdi:calculator'
visible: !include_dir_list ../visibility
badges: []
panel: true
cards: !include ../cards/freebox_button.yaml