#
# Définition de la vue avec les accès autorisés
#
path: temperature
icon: 'mdi:temperature-celsius'
visible: !include_dir_list ../visibility
badges: []
cards:
  - !include ../cards/aqara_1_temperature.yaml
  - !include ../cards/aqara_1_humidity.yaml