#
# Définition de la vue avec les accès autorisés
#
path: weather
icon: 'mdi:theme-light-dark'
visible: !include_dir_list ../visibility
badges: []
cards:
  - !include ../cards/meteo_france_tancarville.yaml