align_icon: left
color_thresholds:
  - color: '#ef1d0f'
    value: 40
  - color: '#ef5a0f'
    value: 45
  - color: '#11f13a'
    value: 60
  - color: '#ef5a0f'
    value: 65
  - color: '#ef1d0f'
    value: 70
entities:
  - sensor.aqara_temp_sdb_humidity
hours_to_show: 24
hour24: true
line_color: '#1da4f2'
more_info: false
name: Salle de bains
points_per_hour: 2
show:
  labels: true
  name: true
type: 'custom:mini-graph-card'