title: "Niveau des batteries"
color_gradient:
  - "#ff0000" # red
  - "#ffff00" # yellow
  - "#00ff00" # green
sort_by_level: "asc"
entities:
  - entity: sensor.controlcenter_niveau_de_batterie
    name: "Control Center"
  # - entity: sensor.aqara_temp_chbre_morgane_battery
  #   name: "Aqara Temp/Hum Chambre Morgane"
  - entity: sensor.aqara_temp_chbre_parents_battery
    name: "Aqara Temp/Hum Chambre Parents"
  - entity: sensor.aqara_temp_sdb_battery
    name: "Aqara Temp/Hum SdB"
  - entity: sensor.aqara_open_sdb_battery
    name: "Aqara Ouverture SdB"
  - entity: sensor.aqara_motion_cellier_battery
    name: "Aqara Mouvement Cellier"
  - entity: sensor.sm_a530f_sg_battery_level
    name: "A8 (Sylvain)"
type: 'custom:battery-state-card'
