type: 'custom:mod-card'
card:
  type: vertical-stack
  cards:
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          color_type: blank-card
        - type: 'custom:button-card'
          color_type: blank-card
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:power'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: power
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-1'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '1'
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-2'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '2'
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-3'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '3'
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-4'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '4'
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-5'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '5'
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-6'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '6'
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-7'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '7'
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-8'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '8'
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-9'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '9'
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          color_type: blank-card
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:numeric-0'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: '0'
        - type: 'custom:button-card'
          color_type: blank-card
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: red
          icon: 'mdi:backspace-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: red
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:arrow-up-bold-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: up
        - type: 'custom:button-card'
          template: blue
          icon: 'mdi:card-search-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: blue
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:arrow-left-bold-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: left
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:checkbox-marked-circle-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: ok
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:arrow-right-bold-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: right
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: green
          icon: 'mdi:menu-open'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: green
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:arrow-down-bold-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: down
        - type: 'custom:button-card'
          template: yellow
          icon: 'mdi:information-variant'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: yellow
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: default
          show_entity_picture: true
          entity_picture: /local/lovelace/jellyfin_logo.png
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: red,right,right,right,right,ok,down,ok
        - type: 'custom:button-card'
          template: default
          show_entity_picture: true
          entity_picture: /local/lovelace/free.png
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: home
        - type: 'custom:button-card'
          template: default
          show_entity_picture: true
          entity_picture: /local/lovelace/330px-Netflix_2015_N_logo.svg.png
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: red,right,down,down,down,ok
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:volume-plus'
          tap_action:
            repeat: 500
            action: call-service
            service: freebox_player.remote
            service_data:
              code: vol_inc
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:volume-mute'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: mute
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:pan-up'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: prgm_inc
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:volume-minus'
          tap_action:
            repeat: 500
            action: call-service
            service: freebox_player.remote
            service_data:
              code: vol_dec
        - type: 'custom:button-card'
          template: default
          color_type: icon
          color: '#A92123'
          icon: 'mdi:record-rec'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: rec
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:pan-down'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: prgm_dec
    - type: horizontal-stack
      cards:
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:skip-backward-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: bwd
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:play-pause'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: play
        - type: 'custom:button-card'
          template: default
          icon: 'mdi:skip-forward-outline'
          tap_action:
            action: call-service
            service: freebox_player.remote
            service_data:
              code: fwd

style: |
  @media (orientation: landscape) {
    ha-card {
      display: none;
    }
  }