align_icon: left
color_thresholds:
  - color: '#11f13a'
    value: 600
  - color: '#11f13a'
    value: 800
  - color: '#f0da11'
    value: 1000
  - color: '#ef5a0f'
    value: 3000
  - color: '#ef1d0f'
    value: 5000
entities:
  - sensor.puissance
hours_to_show: 24
hour24: true
more_info: false
name: Conso EDF
points_per_hour: 2
animate: true
show:
  labels: true
  name: true
type: 'custom:mini-graph-card'