#
# https://github.com/gcorgnet/sensor.emby_upcoming_media
#
platform: emby_upcoming_media
api_key: !secret emby_key
user_id: !secret emby_user_ha
host: !secret emby_host
port: !secret emby_port_https
ssl: true
max: 10
include:
 - Films