#
#
#
title: Hass
order:
  - item: map
    hide: true
  - item: logbook
    hide: true
  - item: history
    hide: true
exceptions:
  - user: admin
    base_order: true
    order:
      - item: map
        hide: false
      - item: developer tools
        hide: true